# Generated by Django 3.2.5 on 2021-08-07 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 12, 12, 38, 641352)),
        ),
    ]
