# Generated by Django 3.2.5 on 2021-08-05 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 11, 4, 56, 887149)),
        ),
    ]
