# Generated by Django 3.2.5 on 2021-08-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetoone',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='onetoone',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='OneToOne',
        ),
    ]
