# Generated by Django 3.2.5 on 2021-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210805_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'A user with that Username already exists.'}, max_length=20, unique=True),
        ),
    ]
